"""empty message

Revision ID: 03ae9a456d10
Revises: 8801bcd28826
Create Date: 2024-09-05 17:27:57.057482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ae9a456d10'
down_revision = '8801bcd28826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('facebook_link')
        batch_op.drop_column('github_link')
        batch_op.drop_column('linkedin_link')
        batch_op.drop_column('description')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
